### ISSUE TITLE
Package installing to wrong location

### ISSUE THREAD

**Issue by jrmoserbaltimore** [ho-tex/pdfcol#1]
On texlive 2022, installing `pdfcol` doesn't resolve xelatex not finding `pdfcol.sty`

On closer examination, `C:\texlive\2022\tex` contains exactly one subdirectory, `latex`, which itself only contains `pdfcol`, which contains `pdfcol.sty`

Moving this to `texmf-dist\tex\latex\pdfcol` works.  I assume the install path is erroneous.

**Comment by u-fischer** [comment]
No the path in texlive looks fine. In my installation it is in `c:/texlive/2022/texmf-dist/tex/latex/pdfcol/pdfcol.sty`. That is the correct place  and xelatex finds it there without problems (but as xelatex has no color stacks it does nothing). If the path doesn't work for you something is wrong with your texlive installation.
